/*
 * The Letters deck: 500 topic prompts.
 * Each round shows a random letter plus two of these prompts;
 * the Judge reads one and players race to answer.
 */
window.LETTERS_TOPICS = [
  // ── Places ─────────────────────────────────────────────
  "City", "Country", "State or province", "Capital city", "Island", "River",
  "Mountain", "Ocean or sea", "Lake", "Desert", "Continent or region",
  "Tourist attraction", "Famous landmark", "Vacation destination",
  "Place to hide", "Place you'd find a crowd", "Room in a house",
  "Store at the mall", "Type of restaurant", "Something at the beach",
  "Something in a park", "Something in a classroom", "Something in a hospital",
  "Something in a garage", "Something in a kitchen", "Something in a bathroom",
  "Something in a bedroom", "Something in an office", "Something at a gas station",
  "Something at an airport", "Something on a farm", "Something in a forest",
  "Something at the zoo", "Something at a circus", "Something at a carnival",
  "Something at a wedding", "Something at a birthday party",
  "Something at a campsite", "Something on a boat", "Something in outer space",

  // ── Food & drink ───────────────────────────────────────
  "Dessert", "Fruit", "Vegetable", "Breakfast food", "Pizza topping",
  "Ice cream flavor", "Candy", "Type of cheese", "Type of bread", "Type of pasta",
  "Soup", "Sandwich", "Fast food item", "Drink", "Cocktail", "Type of juice",
  "Soda brand", "Coffee drink", "Snack food", "Spice or herb", "Condiment",
  "Something you eat with a spoon", "Something you grill", "Something you bake",
  "Something spicy", "Something sweet", "Something sour", "Something salty",
  "Something crunchy", "Something you dip", "Something on a burger",
  "Something in a salad", "Something in a taco", "Something in a smoothie",
  "Something at a picnic", "Holiday food", "Comfort food", "Food that's yellow",
  "Food that's red", "Food that's green", "Food you eat with your hands",
  "Food that comes in a can", "Food that's frozen", "Nut or seed",
  "Type of fish you can eat", "Type of meat", "Cereal brand", "Type of cookie",
  "Cake flavor", "Type of pie",

  // ── Animals & nature ───────────────────────────────────
  "Animal", "Farm animal", "Zoo animal", "Pet", "Dog breed", "Cat breed", "Bird",
  "Fish", "Insect", "Reptile", "Ocean animal", "Animal with fur",
  "Animal with wings", "Animal with a tail", "Animal that's fast",
  "Animal that's slow", "Baby animal name", "Animal sound", "Dinosaur",
  "Mythical creature", "Flower", "Tree", "Plant", "Something in a garden",
  "Weather word", "Something in the sky", "Something that grows",
  "Something found in the ocean", "Gemstone", "Type of rock or mineral",
  "Something that's green", "Something that lives underground",
  "Something with stripes", "Something with spots", "Something that hibernates",
  "Something you'd find in a nest", "Something at a pond", "Natural disaster",
  "Season or month", "Something that stings or bites",

  // ── Something that is… ─────────────────────────────────
  "Something wet", "Something cold", "Something hot", "Something soft",
  "Something hard", "Something sticky", "Something sharp", "Something round",
  "Something square", "Something tiny", "Something huge", "Something heavy",
  "Something light", "Something loud", "Something quiet", "Something fast",
  "Something slow", "Something smelly", "Something shiny", "Something fluffy",
  "Something bumpy", "Something smooth", "Something slippery", "Something fragile",
  "Something you can squeeze", "Something that bounces", "Something that floats",
  "Something that sinks", "Something that melts", "Something that glows",
  "Something that spins", "Something that flies", "Something that rolls",
  "Something that stretches", "Something that breaks easily",
  "Something you plug in", "Something with buttons", "Something with wheels",
  "Something with a handle", "Something with a lid", "Something with strings",
  "Something with teeth", "Something with a screen", "Something made of wood",
  "Something made of metal", "Something made of glass", "Something made of paper",
  "Something made of plastic", "Something made of rubber",
  "Something made of fabric", "Something purple", "Something orange",
  "Something blue", "Something pink", "Something black", "Something white",
  "Something brown", "Something you wear", "Something you wear on your feet",
  "Something you wear on your head", "Something you wear in winter",
  "Something you wear in summer", "Something you carry", "Something you throw",
  "Something you kick", "Something you catch", "Something you push",
  "Something you pull", "Something you fold", "Something you can climb",
  "Something you sit on", "Something you sleep on", "Something you write with",
  "Something you read", "Something you drink from", "Something you eat with",
  "Something you clean with", "Something you cook with", "Something in a toolbox",
  "Something that's bright",

  // ── Everyday things ────────────────────────────────────
  "Piece of furniture", "Kitchen appliance", "Tool", "Toy", "Board game",
  "Video game", "Card game", "Musical instrument", "Vehicle", "Type of boat",
  "Type of ball", "Type of shoe", "Type of hat", "Piece of clothing",
  "Piece of jewelry", "Type of bag", "School supply", "Office supply",
  "Art supply", "Cleaning supply", "Hair product", "Makeup item",
  "Bathroom item", "Baby item", "Camping gear", "Sports equipment",
  "Something in a purse or wallet", "Something in a backpack",
  "Something in a fridge", "Something in a pantry", "Something in a junk drawer",
  "Something in a first aid kit", "Something in a suitcase",
  "Something under a bed", "Something on a desk", "Something on a wall",
  "Something on a keychain", "Something on a Christmas tree",
  "Something in a car", "Something in a hotel room",
  "Something you buy at a pharmacy", "Something you buy at a hardware store",
  "Something you rent", "Something you recycle", "Something that uses batteries",
  "Something with a zipper", "Something with a cord", "Household chore",
  "Kitchen utensil", "Type of fabric",

  // ── Pop culture & entertainment ────────────────────────
  "Movie title", "TV show", "Cartoon character", "Superhero", "Villain",
  "Disney character", "Movie star", "Singer", "Band", "Song title", "Rapper",
  "Fictional character", "Book title", "Children's book", "Author",
  "Comic book character", "Video game character", "Famous athlete",
  "Famous scientist", "Historical figure", "U.S. president", "Famous painter",
  "Famous duo", "Talk show host", "Reality TV show", "Sitcom", "Animated movie",
  "Horror movie", "Romantic comedy", "Action movie", "Movie sequel",
  "Broadway musical", "Fairy tale", "Nursery rhyme", "Christmas movie",
  "Movie with a number in the title", "Song with a color in the title",
  "Boy band", "Pop star", "Country singer", "Movie monster", "Famous robot",
  "Wizard or witch", "Princess", "Pirate", "Superpower", "Catchphrase",
  "Game show", "Emoji", "Internet meme",

  // ── Sports & activities ────────────────────────────────
  "Sport", "Olympic sport", "Water sport", "Winter sport", "Team sport",
  "Sports team", "Football team", "Basketball player", "Baseball term",
  "Yoga pose", "Dance move", "Type of dance", "Magic trick", "Hobby",
  "Outdoor activity", "Indoor activity", "Something you do at the gym",
  "Something you do at a party", "Something you do on vacation",
  "Something you do in the morning", "Something you do before bed",
  "Something you do in the shower", "Something you do with your hands",
  "Something you do with a ball", "Something kids do at recess",
  "Something you do at a sleepover", "Playground equipment", "Carnival ride",
  "Circus act", "Type of exercise",

  // ── People & names ─────────────────────────────────────
  "Job or occupation", "Job that requires a uniform", "Job at a hospital",
  "Job at a school", "Job in a restaurant", "Dangerous job",
  "Job you'd never want", "Boy's name", "Girl's name", "Nickname", "Last name",
  "Name for a pet", "Name for a boat", "Name for a band", "Family member",
  "Famous family", "Type of doctor", "Type of scientist", "Type of teacher",
  "Something a baby does", "Something a teenager says",
  "Something a grandparent says", "Something a teacher says",
  "Something a coach yells", "Something a pirate says", "Something a parent says",
  "Term of endearment", "Something people collect", "Something people fear",
  "Something people argue about",

  // ── Body, health & feelings ────────────────────────────
  "Body part", "Part of the face", "Bone in the body", "Organ in the body",
  "Emotion", "Way to say hello", "Way to say goodbye", "Compliment",
  "Excuse for being late", "Reason to celebrate", "Something that makes you laugh",
  "Something that makes you cry", "Something that makes you sneeze",
  "Something that makes you sleepy", "Something that hurts",
  "Something that itches", "Something people are allergic to",
  "Something contagious", "Something at the doctor's office",
  "Something at the dentist", "Something in a medicine cabinet", "Hairstyle",
  "Facial expression", "Sound your body makes", "Something you do when nervous",

  // ── School, words & science ────────────────────────────
  "School subject", "Language", "Shape", "Color", "Unit of measurement",
  "Planet or moon", "Constellation or star", "Element on the periodic table",
  "Math term", "Science word", "Punctuation mark or grammar term",
  "Something you learn in kindergarten", "Something in a library",
  "Word that rhymes with 'cat'", "Word with a double letter",
  "Word that ends in '-ing'", "Adjective", "Verb", "Word with 3 letters",
  "Word with 10 or more letters", "Compound word", "Word in another language",
  "Slang word", "Sound effect word", "Abbreviation or acronym",
  "Word that means 'happy'", "Word that means 'big'", "Word that means 'fast'",
  "Opposite of 'good'", "Thing that comes in pairs",

  // ── Holidays, brands & money ───────────────────────────
  "Holiday", "Halloween costume", "Christmas gift", "Birthday gift",
  "Valentine's Day gift", "Something on the Thanksgiving table",
  "Something at a parade", "Something at a concert",
  "Something at a football game", "Something at a baseball game",
  "Something on a menu", "Something on a shopping list",
  "Something on a to-do list", "Something in the news", "Car brand", "Car part",
  "Airline", "Clothing brand", "Shoe brand", "Candy brand", "Fast food chain",
  "Store", "App on your phone", "Website", "Social media platform",
  "Something you can download", "Something you subscribe to",
  "Something you pay for monthly", "Something that costs over $1,000",
  "Something you'd find in a piggy bank",

  // ── Silly & creative ───────────────────────────────────
  "Something a dog would say if it could talk", "Bad name for a restaurant",
  "Bad first date activity", "Terrible superhero name",
  "Something you shouldn't microwave", "Thing you'd bring to a desert island",
  "Thing you'd never touch", "Worst thing to find in your bed",
  "Thing you'd hate to step on", "Something that would be a bad pet",
  "Something that would be a bad pillow", "Something in a haunted house",
  "Something a robot might do", "Something a ghost would say",
  "Something in a wizard's pocket", "Excuse for missing homework",
  "Something you'd shout at a sports game", "Something that's overrated",
  "Something that's underrated", "Something you'd never buy used",
  "Something that smells great", "Something that smells terrible",
  "Something you yell when scared", "Something you'd put in a time capsule",
  "Something a villain would own", "Something you hide from your parents",
  "Something that gets stuck", "Something you lose all the time",
  "Thing to buy with a million dollars", "Something at a garage sale",
  "Something on the floor of a car", "Something money can't buy",
  "Something you'd never wear to a wedding",
  "Something a cat would knock off a table", "Something that's better in the dark",
  "Something that's better cold", "Thing that doesn't belong on a sandwich",
  "Name for a superhero's sidekick", "Name for a pet rock", "Name for a spaceship",
  "Thing a magician pulls from a hat", "Thing in a pirate's treasure chest",
  "Something you'd pack for the moon", "Something you can juggle",
  "Something that would make a terrible gift"
];
