/*
 * The Letters deck of topic prompts.
 * Each round shows a random letter plus two of these prompts;
 * the Judge reads one and players race to answer.
 *
 * Prompts are kept deliberately easy: broad categories with lots of
 * possible answers for almost any letter. Narrow or brainy topics
 * (periodic table, constellations, yoga poses…) are left out on purpose.
 */
window.LETTERS_TOPICS = [
  // ── Wide open ──────────────────────────────────────────
  "Any animal", "Any food", "Any place", "Any name", "Any word",
  "Anything in this room", "Anything you can see right now",
  "Anything you can buy", "Anything you can eat", "Anything you can hold",
  "Anything that's alive", "Anything bigger than a car",
  "Anything smaller than your hand", "Anything with a motor",
  "Something you own", "Something you want", "Something you love",
  "Something you hate", "Something you'd never eat", "Something that's free",
  "Something you see every day", "Something you did today",
  "Something you'd find in a house", "Something you'd find at school",
  "Something you'd find outside", "Something you'd find in a city",
  "Something you'd find in the country", "Something you'd find at a store",
  "Something you'd find at a party", "Something you'd find at work",

  // ── Places ─────────────────────────────────────────────
  "City", "Country", "State", "Island", "River", "Mountain", "Lake",
  "Tourist attraction", "Famous landmark", "Vacation spot", "Beach town",
  "Place to hide", "Place you'd find a crowd", "Place you'd take a date",
  "Place you'd take kids", "Place you go on a Saturday", "Place that's noisy",
  "Place that's quiet", "Place that's crowded", "Place that's cold",
  "Place that's hot", "Room in a house", "Store at the mall",
  "Type of restaurant", "Something at the beach", "Something in a park",
  "Something in a classroom", "Something in a hospital", "Something in a garage",
  "Something in a kitchen", "Something in a bathroom", "Something in a bedroom",
  "Something in a living room", "Something in a basement", "Something in an attic",
  "Something in a backyard", "Something in an office", "Something at a gas station",
  "Something at an airport", "Something on a farm", "Something in a forest",
  "Something at the zoo", "Something at a circus", "Something at a carnival",
  "Something at a wedding", "Something at a birthday party",
  "Something at a campsite", "Something on a boat", "Something in outer space",
  "Something at a grocery store", "Something at a hardware store",
  "Something at a movie theater", "Something at a playground",
  "Something at a swimming pool", "Something at a gym", "Something at a bar",
  "Something at a coffee shop", "Something at a hotel", "Something at church",
  "Something at a mall", "Something at a stadium", "Something at a museum",
  "Something at a bus stop", "Something on a sidewalk", "Something on a road",
  "Something in a parking lot", "Something in a waiting room",
  "Something in a locker room", "Something in a school cafeteria",
  "Something in a dorm room", "Something in a nursery", "Something in a barn",
  "Something at a lake", "Something in a river", "Something on a mountain",
  "Something in a cave", "Something in a jungle", "Something in the desert",
  "Something in a snowstorm", "Something on an island",

  // ── Food & drink ───────────────────────────────────────
  "Food", "Dessert", "Fruit", "Vegetable", "Breakfast food", "Lunch food",
  "Dinner food", "Pizza topping", "Ice cream flavor", "Candy", "Chocolate bar",
  "Type of cheese", "Type of bread", "Type of pasta", "Soup", "Sandwich",
  "Fast food item", "Drink", "Cocktail", "Type of juice", "Soda", "Coffee drink",
  "Snack food", "Chip flavor", "Spice or herb", "Condiment", "Sauce",
  "Something you eat with a spoon", "Something you eat with a fork",
  "Something you grill", "Something you bake", "Something you fry",
  "Something you boil", "Something you microwave", "Something spicy",
  "Something sweet", "Something sour", "Something salty", "Something crunchy",
  "Something chewy", "Something creamy", "Something you dip",
  "Something on a burger", "Something on a hot dog", "Something in a salad",
  "Something in a taco", "Something in a burrito", "Something in a smoothie",
  "Something in a sandwich", "Something in a stew", "Something on toast",
  "Something on a bagel", "Something on pancakes", "Something at a picnic",
  "Something at a barbecue", "Something at a potluck", "Something in a lunchbox",
  "Something at a bake sale", "Something at a buffet", "Something at a food truck",
  "Holiday food", "Comfort food", "Junk food", "Health food", "Party food",
  "Movie theater snack", "Road trip snack", "Midnight snack", "Food that's yellow",
  "Food that's red", "Food that's green", "Food that's white", "Food that's brown",
  "Food that's orange", "Food you eat with your hands", "Food that comes in a can",
  "Food that comes in a box", "Food that comes in a bag", "Food that's frozen",
  "Food that's messy", "Food kids love", "Food kids hate", "Food that's round",
  "Food on a stick", "Food you eat cold", "Food you eat hot", "Nut or seed",
  "Type of fish you can eat", "Type of meat", "Cereal", "Type of cookie",
  "Cake flavor", "Type of pie", "Type of donut", "Type of cracker",
  "Type of potato dish", "Type of egg dish", "Type of noodle dish",
  "Something with chocolate in it", "Something with cheese on it",
  "Something you put sugar in", "Something you put salt on",
  "Something you put ketchup on", "Something you drink in the morning",
  "Something you drink at night", "Something you drink when sick",
  "Something in a fridge", "Something in a pantry", "Something in a cooler",
  "Something in a vending machine", "Something on a kids' menu",
  "Something on a pizza menu", "Something on a breakfast menu",
  "Something at Thanksgiving dinner", "Something at a Christmas dinner",
  "Something at a Fourth of July cookout", "Something on an Easter table",
  "Halloween candy", "Thing in a trick-or-treat bag",

  // ── Animals & nature ───────────────────────────────────
  "Animal", "Farm animal", "Zoo animal", "Wild animal", "Pet", "Dog breed",
  "Bird", "Fish", "Insect", "Bug", "Reptile", "Ocean animal", "Forest animal",
  "Jungle animal", "Animal with fur", "Animal with wings", "Animal with a tail",
  "Animal with horns", "Animal with four legs", "Animal that's fast",
  "Animal that's slow", "Animal that's big", "Animal that's small",
  "Animal that's cute", "Animal that's scary", "Animal that swims",
  "Animal that climbs", "Animal that digs", "Animal you can ride",
  "Animal you'd see at a pet store", "Animal in a cartoon", "Animal in a kids' book",
  "Animal sound", "Dinosaur", "Mythical creature", "Flower", "Tree", "Plant",
  "Something in a garden", "Weather word", "Something in the sky",
  "Something that grows", "Something found in the ocean", "Something that's green",
  "Something that lives underground", "Something with stripes",
  "Something with spots", "Something you'd find in a nest", "Something at a pond",
  "Something that stings or bites", "Something that crawls",
  "Something that flies", "Something that swims", "Something that hops",
  "Something that lives in a tree", "Something that lives in water",
  "Something you'd see on a hike", "Something you'd see at the beach",
  "Something you'd see on a farm", "Something you'd see in a creek",

  // ── Something that is… ─────────────────────────────────
  "Something wet", "Something dry", "Something cold", "Something hot",
  "Something soft", "Something hard", "Something sticky", "Something sharp",
  "Something round", "Something square", "Something flat", "Something long",
  "Something tiny", "Something huge", "Something heavy", "Something light",
  "Something loud", "Something quiet", "Something fast", "Something slow",
  "Something smelly", "Something shiny", "Something fluffy", "Something bumpy",
  "Something smooth", "Something slippery", "Something fragile",
  "Something stretchy", "Something squishy", "Something scratchy",
  "Something warm", "Something ugly", "Something pretty", "Something cute",
  "Something scary", "Something gross", "Something fun", "Something boring",
  "Something expensive", "Something cheap", "Something old", "Something new",
  "Something dangerous", "Something safe", "Something messy", "Something clean",
  "Something stinky", "Something delicious", "Something colorful",
  "Something striped", "Something you can squeeze", "Something that bounces",
  "Something that floats", "Something that sinks", "Something that melts",
  "Something that glows", "Something that spins", "Something that rolls",
  "Something that breaks easily", "Something that gets dirty",
  "Something that makes noise", "Something that smells good",
  "Something that smells bad", "Something that's always moving",
  "Something you plug in", "Something with buttons", "Something with wheels",
  "Something with a handle", "Something with a lid", "Something with strings",
  "Something with teeth", "Something with a screen", "Something with a tail",
  "Something with legs", "Something with a door", "Something with a light",
  "Something with a key", "Something with wings", "Something made of wood",
  "Something made of metal", "Something made of glass", "Something made of paper",
  "Something made of plastic", "Something made of rubber",
  "Something made of fabric", "Something made of stone", "Something purple",
  "Something orange", "Something blue", "Something pink", "Something black",
  "Something white", "Something brown", "Something red", "Something yellow",
  "Something gray", "Something gold", "Something silver",
  "Something you wear", "Something you wear on your feet",
  "Something you wear on your head", "Something you wear on your hands",
  "Something you wear in winter", "Something you wear in summer",
  "Something you wear to bed", "Something you wear to a wedding",
  "Something you wear to the gym", "Something you wear in the rain",
  "Something you carry", "Something you throw", "Something you kick",
  "Something you catch", "Something you push", "Something you pull",
  "Something you fold", "Something you can climb", "Something you sit on",
  "Something you sleep on", "Something you write with", "Something you read",
  "Something you drink from", "Something you eat with", "Something you clean with",
  "Something you cook with", "Something you cut with", "Something you open",
  "Something you close", "Something you turn on", "Something you wash",
  "Something you hang up", "Something you lock", "Something you share",
  "Something you borrow", "Something you lose", "Something you collect",
  "Something you wrap", "Something you water", "Something you charge",
  "Something you ride", "Something you drive", "Something you build",
  "Something you draw", "Something you sing", "Something you watch",
  "Something you play", "Something in a toolbox", "Something that's bright",

  // ── Everyday things ────────────────────────────────────
  "Piece of furniture", "Kitchen appliance", "Tool", "Toy", "Board game",
  "Video game", "Card game", "Playground game", "Musical instrument", "Vehicle",
  "Type of truck", "Type of boat", "Type of ball", "Type of shoe", "Type of hat",
  "Type of coat", "Piece of clothing", "Piece of jewelry", "Type of bag",
  "School supply", "Office supply", "Art supply", "Cleaning supply",
  "Hair product", "Makeup item", "Bathroom item", "Baby item", "Camping gear",
  "Sports equipment", "Something in a purse or wallet", "Something in a backpack",
  "Something in a junk drawer", "Something in a first aid kit",
  "Something in a suitcase", "Something in a closet", "Something in a drawer",
  "Something in a glove box", "Something in a diaper bag",
  "Something in a gym bag", "Something in a desk drawer",
  "Something under a bed", "Something under a couch", "Something on a desk",
  "Something on a wall", "Something on a shelf", "Something on a nightstand",
  "Something on a keychain", "Something on a Christmas tree",
  "Something on a kitchen counter", "Something on a coffee table",
  "Something in a car", "Something in a hotel room", "Something in a mailbox",
  "Something you buy at a pharmacy", "Something you buy at a gas station",
  "Something you buy at a dollar store", "Something you buy online",
  "Something you'd buy at Target", "Something you'd buy at Costco",
  "Something you rent", "Something you recycle", "Something you throw away",
  "Something that uses batteries", "Something with a zipper",
  "Something with a cord", "Something with a plug", "Household chore",
  "Kitchen utensil", "Thing in a laundry room", "Thing in a toolbox",
  "Thing in a sewing kit", "Thing in a makeup bag", "Thing in a tackle box",
  "Thing on a bike", "Thing on a car", "Thing on a boat", "Thing on a plane",
  "Thing in a hospital room", "Thing in a dentist's office",
  "Thing in a classroom", "Thing in a church", "Thing at a wedding",
  "Thing at a funeral", "Thing in a bar", "Thing in a casino",
  "Thing at a concert", "Thing at a football game", "Thing at a baseball game",
  "Thing at a parade", "Thing at a fair", "Thing at a water park",
  "Thing at a theme park", "Thing at a ski resort", "Thing at a garage sale",
  "Thing at a car wash", "Thing you'd find in a lost and found",

  // ── Pop culture & entertainment ────────────────────────
  "Movie", "TV show", "Cartoon", "Cartoon character", "Superhero", "Villain",
  "Disney character", "Disney movie", "Pixar character", "Marvel character",
  "Star Wars character", "Harry Potter character", "Nintendo character",
  "Pokémon", "Muppet", "Sesame Street character", "Movie star", "Celebrity",
  "Famous person", "Singer", "Band", "Song", "Rapper", "Famous athlete",
  "Famous person from history", "U.S. president", "Fictional character",
  "Book", "Children's book", "Comic book character", "Video game character",
  "Reality TV show", "Sitcom", "Animated movie", "Horror movie",
  "Romantic comedy", "Action movie", "Movie sequel", "Fairy tale",
  "Nursery rhyme", "Christmas movie", "Christmas song", "Kids' movie",
  "Movie with an animal in it", "Movie with a number in the title",
  "Song with a color in the title", "Song you know all the words to",
  "Song you'd sing at karaoke", "Song you'd dance to at a wedding",
  "Boy band", "Pop star", "Country singer", "Movie monster", "Famous robot",
  "Wizard or witch", "Princess", "Pirate", "Cowboy word", "Superpower",
  "Catchphrase", "Game show", "Emoji", "Internet meme", "YouTube channel",
  "TikTok trend", "Famous dog", "Famous cat", "Famous mouse", "Famous bear",
  "Famous duo", "TV family", "TV dad", "TV mom", "Famous couple",
  "Famous chef", "Famous wrestler", "Famous race car driver",
  "Something in a superhero movie", "Something in a horror movie",
  "Something in a western", "Something in a spy movie",
  "Something in a cartoon", "Something at a movie premiere",
  "Something you'd see at a concert", "Something a DJ says",

  // ── Sports & activities ────────────────────────────────
  "Sport", "Olympic sport", "Team sport", "Sports team", "Football team",
  "Baseball team", "Basketball team", "College mascot", "Team mascot",
  "Sports position", "Thing a referee does", "Sports word", "Football word",
  "Baseball word", "Basketball word", "Soccer word", "Golf word",
  "Thing you'd see at a gym", "Type of dance", "Dance move", "Hobby",
  "Outdoor activity", "Indoor activity", "Rainy day activity",
  "Summer activity", "Winter activity", "Beach activity", "Pool activity",
  "Something you do at the gym", "Something you do at a party",
  "Something you do on vacation", "Something you do in the morning",
  "Something you do before bed", "Something you do in the shower",
  "Something you do with your hands", "Something you do with a ball",
  "Something you do with friends", "Something you do alone",
  "Something you do on a snow day", "Something you do at a sleepover",
  "Something you do at camp", "Something you do at a wedding",
  "Something you do at a birthday party", "Something you do on a road trip",
  "Something you do on a plane", "Something you do in a car",
  "Something you do at recess", "Something kids do at recess",
  "Something you do in the snow", "Something you do at the lake",
  "Something you do in your backyard", "Playground equipment",
  "Type of exercise", "Thing you do to stay healthy", "Thing you do when bored",
  "Thing you do when it rains", "Thing you do on your phone",
  "Thing you do in the kitchen", "Thing you do on the weekend",

  // ── People & names ─────────────────────────────────────
  "Job", "Job that requires a uniform", "Job at a hospital", "Job at a school",
  "Job in a restaurant", "Job at a store", "Job outdoors", "Dangerous job",
  "Job you'd never want", "Job you wanted as a kid", "Job that pays well",
  "Boy's name", "Girl's name", "Baby name", "Old-fashioned name", "Nickname",
  "Last name", "Name for a pet", "Name for a dog", "Name for a cat",
  "Name for a goldfish", "Name for a boat", "Name for a band",
  "Name of someone you know", "Name of a famous person", "Name of a teacher",
  "Family member", "Type of doctor", "Type of teacher", "Type of nurse",
  "Something a baby does", "Something a toddler says",
  "Something a teenager says", "Something a grandparent says",
  "Something a teacher says", "Something a coach yells",
  "Something a pirate says", "Something a parent says",
  "Something a boss says", "Something a cop says", "Something a doctor says",
  "Something a waiter says", "Something a flight attendant says",
  "Something a cashier says", "Something a bride says",
  "Something a dog would say if it could talk",
  "Something a cat would say if it could talk", "Term of endearment",
  "Something people collect", "Something people fear",
  "Something people argue about", "Something people brag about",
  "Something people complain about", "Something people wait in line for",
  "Something people lie about", "Something people are proud of",
  "Something people do when nervous", "Something people do when bored",
  "Something people yell at the TV", "Something people say on the phone",
  "Something people say at a restaurant", "Something people say in traffic",

  // ── Body, health & feelings ────────────────────────────
  "Body part", "Part of the face", "Part of the hand", "Part of the leg",
  "Emotion", "Way to say hello", "Way to say goodbye", "Way to say thanks",
  "Way to say sorry", "Compliment", "Insult (a nice one!)",
  "Excuse for being late", "Reason to celebrate", "Reason to call in sick",
  "Something that makes you laugh", "Something that makes you cry",
  "Something that makes you sneeze", "Something that makes you sleepy",
  "Something that makes you happy", "Something that makes you mad",
  "Something that makes you nervous", "Something that makes you hungry",
  "Something that hurts", "Something that itches", "Something that tickles",
  "Something people are allergic to", "Something contagious",
  "Something at the doctor's office", "Something at the dentist",
  "Something in a medicine cabinet", "Hairstyle", "Hair color",
  "Facial expression", "Sound your body makes", "Something you do when nervous",
  "Something you do when you're sick", "Something you do when you're tired",
  "Something you do when you're happy", "Something you do when you're mad",
  "Thing you can break", "Thing you can bruise", "Thing you can sprain",
  "Reason to go to the hospital", "Reason to see a doctor",

  // ── School, words & simple stuff ───────────────────────
  "School subject", "Language", "Shape", "Color", "Number word",
  "Something you learn in kindergarten", "Something in a library",
  "Word with a double letter", "Word that ends in '-ing'", "Word with 3 letters",
  "Word with 4 letters", "Compound word", "Word in another language",
  "Slang word", "Sound effect word", "Verb", "Adjective", "Action word",
  "Describing word", "Thing that comes in pairs", "Thing that comes in a dozen",
  "Thing that comes in a six-pack", "Something on a spelling test",
  "Something you'd see on a flash card", "Something in a math class",
  "Something in a science class", "Something in a gym class",
  "Something in a music class", "Something in an art class",
  "Something you need for school", "Something in a teacher's desk",
  "Something on a report card", "Something in a yearbook",
  "Thing you'd see on a map", "Thing you'd see on a calendar",
  "Thing you'd see on a clock", "Thing you'd see in a dictionary",

  // ── Holidays, brands & money ───────────────────────────
  "Holiday", "Halloween costume", "Christmas gift", "Birthday gift",
  "Valentine's Day gift", "Mother's Day gift", "Father's Day gift",
  "Wedding gift", "Housewarming gift", "Graduation gift", "Baby shower gift",
  "Stocking stuffer", "Christmas decoration", "Halloween decoration",
  "Something on the Thanksgiving table", "Something at a parade",
  "Something at a concert", "Something at a football game",
  "Something at a baseball game", "Something on a menu",
  "Something on a shopping list", "Something on a to-do list",
  "Something on a wish list", "Something on a packing list",
  "Something in the news", "Car brand", "Car part", "Truck brand",
  "Clothing brand", "Shoe brand", "Candy brand", "Fast food chain",
  "Restaurant chain", "Store", "Grocery store", "Department store",
  "Gas station chain", "Cereal brand", "Soda brand", "Snack brand",
  "Toy brand", "Phone brand", "App on your phone", "Website",
  "Social media platform", "Streaming service", "Something you can download",
  "Something you subscribe to", "Something you pay for monthly",
  "Something that costs over $1,000", "Something that costs under $5",
  "Something you'd find in a piggy bank", "Something you save up for",
  "Something you'd buy with your first paycheck", "Something on sale",
  "Something you'd buy at a gift shop", "Something you'd win at a carnival",
  "Something in a gift basket", "Something in a goodie bag",
  "Something in a piñata", "Something in a lunch bag",

  // ── Silly & creative ───────────────────────────────────
  "Bad name for a restaurant", "Bad name for a dog", "Bad first date activity",
  "Terrible superhero name", "Something you shouldn't microwave",
  "Thing you'd bring to a desert island", "Thing you'd never touch",
  "Worst thing to find in your bed", "Worst thing to find in your food",
  "Worst thing to step on", "Something that would be a bad pet",
  "Something that would be a bad pillow", "Something that would be a bad hat",
  "Something in a haunted house", "Something a robot might do",
  "Something a ghost would say", "Something in a wizard's pocket",
  "Something in a clown's pocket", "Something in a kid's pocket",
  "Excuse for missing homework", "Excuse for not doing the dishes",
  "Something you'd shout at a sports game", "Something that's overrated",
  "Something that's underrated", "Something you'd never buy used",
  "Something that smells great", "Something that smells terrible",
  "Something you yell when scared", "Something you yell when you win",
  "Something you'd put in a time capsule", "Something a villain would own",
  "Something you hide from your parents", "Something you hide from your kids",
  "Something that gets stuck", "Something you lose all the time",
  "Thing to buy with a million dollars", "Something at a garage sale",
  "Something on the floor of a car", "Something money can't buy",
  "Something you'd never wear to a wedding",
  "Something a cat would knock off a table", "Something that's better in the dark",
  "Something that's better cold", "Something that's better with cheese",
  "Thing that doesn't belong on a sandwich", "Thing that doesn't belong on a pizza",
  "Name for a superhero's sidekick", "Name for a pet rock", "Name for a spaceship",
  "Name for a roller coaster", "Name for a race horse", "Name for a wrestler",
  "Thing a magician pulls from a hat", "Thing in a pirate's treasure chest",
  "Something you'd pack for the moon", "Something you can juggle",
  "Something that would make a terrible gift", "Something you'd regift",
  "Something you'd find in a dragon's cave", "Something a baby would throw",
  "Something a toddler would put in their mouth", "Something a dog would chew",
  "Something a monkey would steal", "Something you'd see in a dream",
  "Something you'd see in a nightmare", "Something that would ruin a picnic",
  "Something that would ruin a road trip", "Something you'd never say to your boss",
  "Something you'd never say to a cop", "Something you'd never say at a wedding",
  "Something you'd name a boat if you were a pirate",
  "Something that's embarrassing", "Something that's annoying",
  "Something that's awkward", "Something that's weird", "Something that's wild",
  "Something you'd do for a dollar", "Something you wouldn't do for a million dollars"
];
